debug: true
root_directory: ""
log_directory: "."
# Set the value of the URI variable with your MongoDB Atlas connection string
mongodb_uri: "mongodb+srv://latifa:latifa@cluster0.yidqc.mongodb.net/?retryWrites=true&w=majority"
google_cloud:
  storage:
    credentials_file: "./google-cloud-creds.json"
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false